-- Remove RBD datasource and all realated content
DELETE FROM classifications USING datasources WHERE datasources.name = 'RBdigital' AND classifications.data_source_id = datasources.id;
DELETE FROM coveragerecords USING datasources WHERE datasources.name = 'RBdigital' AND coveragerecords.data_source_id = datasources.id;
DELETE FROM contributions USING editions,datasources WHERE contributions.edition_id = editions.id AND editions.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM customlistentries USING editions,datasources WHERE customlistentries.edition_id = editions.id AND editions.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM editions USING datasources WHERE editions.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM equivalents USING datasources WHERE equivalents.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM hyperlinks USING datasources WHERE hyperlinks.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM licensepooldeliveries USING datasources WHERE licensepooldeliveries.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM contributions USING editions,resources,datasources WHERE editions.cover_id = resources.id AND contributions.edition_id = editions.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM customlistentries USING editions,resources,datasources WHERE editions.cover_id = resources.id AND customlistentries.edition_id = editions.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM circulationevents USING editions,resources,licensepools,datasources WHERE editions.cover_id = resources.id AND licensepools.presentation_edition_id = editions.id AND circulationevents.license_pool_id = licensepools.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM licensepools USING editions,resources,datasources WHERE editions.cover_id = resources.id AND licensepools.presentation_edition_id = editions.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM workcoveragerecords USING editions,resources,works,datasources WHERE editions.cover_id = resources.id AND works.presentation_edition_id = editions.id AND workcoveragerecords.work_id = works.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM workgenres USING editions,resources,works,datasources WHERE editions.cover_id = resources.id AND works.presentation_edition_id = editions.id AND workgenres.work_id = works.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM works USING editions,resources,datasources WHERE editions.cover_id = resources.id AND works.presentation_edition_id = editions.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM editions using resources,datasources WHERE editions.cover_id = resources.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM circulationevents USING works,resources,licensepools,datasources WHERE works.summary_id = resources.id AND licensepools.work_id = works.id AND circulationevents.license_pool_id = licensepools.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM licensepools USING works,resources,datasources WHERE works.summary_id = resources.id AND licensepools.work_id = works.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM workcoveragerecords USING resources,works,datasources WHERE works.summary_id = resources.id AND workcoveragerecords.work_id = works.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM workgenres USING resources,works,datasources WHERE works.summary_id = resources.id AND workgenres.work_id = works.id  AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM works USING resources,datasources WHERE works.summary_id = resources.id AND resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM resources USING datasources WHERE resources.data_source_id = datasources.id AND datasources.name = 'RBdigital';
DELETE FROM datasources WHERE datasources.name = 'RBdigital';

-- Remove RBD externalintegration, its related collections and all related content
DELETE FROM configurationsettings USING externalintegrations WHERE configurationsettings.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM externalintegrations_libraries USING externalintegrations WHERE externalintegrations_libraries.externalintegration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM collections_libraries USING collections, externalintegrations WHERE collections_libraries.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM coveragerecords USING collections, externalintegrations WHERE coveragerecords.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM credentials USING collections, externalintegrations WHERE credentials.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM circulationevents USING licensepools, collections, externalintegrations WHERE circulationevents.license_pool_id = licensepools.id AND licensepools.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM holds USING licensepools, collections, externalintegrations WHERE holds.license_pool_id = licensepools.id AND licensepools.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM loans USING licensepools, collections, externalintegrations WHERE loans.license_pool_id = licensepools.id AND licensepools.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM complaints USING licensepools, collections, externalintegrations WHERE complaints.license_pool_id = licensepools.id AND licensepools.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM licensepools USING collections, externalintegrations WHERE licensepools.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM timestamps USING collections, externalintegrations WHERE timestamps.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM collections_customlists USING collections, externalintegrations WHERE collections_customlists.collection_id = collections.id AND collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM collections USING externalintegrations WHERE collections.external_integration_id = externalintegrations.id AND externalintegrations.protocol = 'RBdigital';
DELETE FROM externalintegrations WHERE externalintegrations.protocol = 'RBdigital';
