# Reference: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        threshold: 0.2%

comment:
  # Only comment when coverage changes
  require_changes: true
  # Require all builds to finish before comment is posted
  layout: "reach, diff, flags, files"

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.2%
      - type: patch
        target: auto
