# Reference: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        threshold: 0.2%

comment:
  # Only comment when coverage changes
  require_changes: true
  # Require all builds to finish before comment is posted
  after_n_builds: 8
