# Reference: https://docs.codecov.com/docs/codecovyml-reference

comment:
  # Only comment when coverage changes
  require_changes: true
  # Require all builds to finish before comment is posted
  after_n_builds: 8
