changelog:
  exclude:
    labels:
      - ignore for notes
  categories:
    - title: Incompatible Changes
      labels:
        - incompatible changes
    - title: Features
      labels:
        - feature
    - title: Bugfixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependency Updates
      labels:
        - dependencies
