#!/bin/bash
set -e

# Set the working directory to the root of the project
cd /var/www/circulation
source env/bin/activate

# Make sure the log directory exists and is writable
mkdir -p /var/log/celery
chown palace:adm /var/log/celery

# Start the celery worker
exec env/bin/celery -A "palace.manager.celery.app" worker --uid palace --gid palace --concurrency 8 --hostname default@%h -Q high,default --logfile /var/log/celery/default.log
