#!/usr/bin/env python
"""Run any new migrations from the database"""
import startup  # noqa: autoflake
from core.scripts import DatabaseMigrationInitializationScript

DatabaseMigrationInitializationScript().run()
