pytest_plugins = [
    "tests.fixtures.announcements",
    "tests.fixtures.csv_files",
    "tests.fixtures.container",
    "tests.fixtures.database",
    "tests.fixtures.library",
    "tests.fixtures.opds2_files",
    "tests.fixtures.opds_files",
    "tests.fixtures.s3",
    "tests.fixtures.sample_covers",
    "tests.fixtures.search",
    "tests.fixtures.services",
    "tests.fixtures.time",
    "tests.fixtures.tls_server",
]
