"""Audiobook playtime tracking

Revision ID: 892c8e0c89f8
Revises: b3749bac3e55
Create Date: 2023-07-28 07:20:24.625484+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "892c8e0c89f8"
down_revision = "b3749bac3e55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playtime_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_seconds_played", sa.Integer(), nullable=False),
        sa.Column("tracking_id", sa.String(length=64), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["identifier_id"],
            ["identifiers.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["library_id"], ["libraries.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identifier_id", "collection_id", "library_id", "tracking_id"
        ),
    )
    op.create_table(
        "playtime_summaries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier_id", sa.Integer(), nullable=True),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("identifier_str", sa.String(), nullable=False),
        sa.Column("collection_name", sa.String(), nullable=False),
        sa.Column("library_name", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_seconds_played", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["identifier_id"],
            ["identifiers.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["library_id"], ["libraries.id"], onupdate="CASCADE", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "identifier_str", "collection_name", "library_name", "timestamp"
        ),
    )
    op.create_index(
        op.f("ix_playtime_summaries_collection_id"),
        "playtime_summaries",
        ["collection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playtime_summaries_identifier_id"),
        "playtime_summaries",
        ["identifier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_playtime_summaries_library_id"),
        "playtime_summaries",
        ["library_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_playtime_summaries_library_id"), table_name="playtime_summaries"
    )
    op.drop_index(
        op.f("ix_playtime_summaries_identifier_id"), table_name="playtime_summaries"
    )
    op.drop_index(
        op.f("ix_playtime_summaries_collection_id"), table_name="playtime_summaries"
    )
    op.drop_table("playtime_summaries")
    op.drop_table("playtime_entries")
    # ### end Alembic commands ###
