"""Remove external integration from collection.

Revision ID: ee1e46db7352
Revises: cc084e35e037
Create Date: 2023-11-01 16:06:02.913999+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ee1e46db7352"
down_revision = "cc084e35e037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_collections_libraries_collection_id", table_name="collections_libraries"
    )
    op.drop_index(
        "ix_collections_libraries_library_id", table_name="collections_libraries"
    )
    op.drop_table("collections_libraries")
    op.alter_column(
        "collections",
        "integration_configuration_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index("ix_collections_external_integration_id", table_name="collections")
    op.drop_index("ix_collections_name", table_name="collections")
    op.drop_constraint(
        "collections_external_integration_id_fkey", "collections", type_="foreignkey"
    )
    op.drop_column("collections", "name")
    op.drop_column("collections", "external_account_id")
    op.drop_column("collections", "external_integration_id")
    op.add_column(
        "integration_configurations",
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.create_index(
        "ix_integration_configurations_settings_dict",
        "integration_configurations",
        ["settings"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_integration_configurations_settings_dict",
        table_name="integration_configurations",
        postgresql_using="gin",
    )
    op.drop_column("integration_configurations", "context")
    op.add_column(
        "collections",
        sa.Column(
            "external_integration_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "collections",
        sa.Column(
            "external_account_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "collections",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "collections_external_integration_id_fkey",
        "collections",
        "externalintegrations",
        ["external_integration_id"],
        ["id"],
    )
    op.create_index("ix_collections_name", "collections", ["name"], unique=False)
    op.create_index(
        "ix_collections_external_integration_id",
        "collections",
        ["external_integration_id"],
        unique=False,
    )
    op.alter_column(
        "collections",
        "integration_configuration_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.create_table(
        "collections_libraries",
        sa.Column("collection_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("library_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name="collections_libraries_collection_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
            name="collections_libraries_library_id_fkey",
        ),
        sa.UniqueConstraint(
            "collection_id",
            "library_id",
            name="collections_libraries_collection_id_library_id_key",
        ),
    )
    op.create_index(
        "ix_collections_libraries_library_id",
        "collections_libraries",
        ["library_id"],
        unique=False,
    )
    op.create_index(
        "ix_collections_libraries_collection_id",
        "collections_libraries",
        ["collection_id"],
        unique=False,
    )
    # ### end Alembic commands ###
