"""Migrate library settings

Revision ID: b3749bac3e55
Revises: 3d380776c1bf
Create Date: 2023-07-19 16:13:14.831349+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b3749bac3e55"
down_revision = "3d380776c1bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "libraries",
        sa.Column(
            "settings_dict", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("libraries", "settings_dict")
    # ### end Alembic commands ###
