"""Playtime tracking

Revision ID: 4476624597a5
Revises: 3d380776c1bf
Create Date: 2023-07-20 09:30:39.384787+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4476624597a5"
down_revision = "3d380776c1bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.create_table(
        "identifier_playtime_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_seconds_played", sa.Integer(), nullable=False),
        sa.Column("tracking_id", sa.String(length=64), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["identifier_id"],
            ["identifiers.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier_id", "tracking_id"),
    )
    op.create_table(
        "identifier_playtimes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("identifier_id", sa.Integer(), nullable=True),
        sa.Column("identifier_str", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("total_seconds_played", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["identifier_id"],
            ["identifiers.id"],
            onupdate="CASCADE",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identifier_str", "timestamp"),
    )
    op.create_index(
        op.f("ix_identifier_playtimes_identifier_id"),
        "identifier_playtimes",
        ["identifier_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(
        op.f("ix_identifier_playtimes_identifier_id"), table_name="identifier_playtimes"
    )
    op.drop_table("identifier_playtimes")
    op.drop_table("identifier_playtime_entries")
    # ### end Alembic commands ###
