"""Loan and hold notification times

Revision ID: 21a65b8f391d
Revises: 5d71a80073d5
Create Date: 2023-10-16 09:46:58.743018+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "21a65b8f391d"
down_revision = "5d71a80073d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "holds", sa.Column("patron_last_notified", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "loans", sa.Column("patron_last_notified", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("loans", "patron_last_notified")
    op.drop_column("holds", "patron_last_notified")
    # ### end Alembic commands ###
