"""Integration status

Revision ID: 3d5db04dc99b
Revises: 0c2fe32b5649
Create Date: 2023-04-04 06:08:31.728590+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3d5db04dc99b"
down_revision = "0c2fe32b5649"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.add_column(
        "externalintegrations",
        sa.Column("status", sa.Integer(), server_default="1", nullable=True),
    )
    op.add_column(
        "externalintegrations",
        sa.Column("last_status_update", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_column("externalintegrations", "last_status_update")
    op.drop_column("externalintegrations", "status")
    # ### end Alembic commands ###
