"""Update database nullable constraints

Revision ID: e8ba89a7585a
Revises: 272da5f400de
Create Date: 2024-11-27 17:44:03.526711+00:00

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e8ba89a7585a"
down_revision = "272da5f400de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "customlists",
        "auto_update_status",
        existing_type=postgresql.ENUM(
            "init", "updated", "repopulate", name="auto_update_status"
        ),
        nullable=False,
    )
    op.alter_column(
        "editions", "data_source_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "editions", "primary_identifier_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "equivalents", "input_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "equivalentscoveragerecords",
        "equivalency_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("holds", "patron_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "holds", "license_pool_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("lanes", "display_name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "licensepools", "data_source_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "licensepools", "identifier_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "licensepools", "licenses_owned", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "licensepools", "licenses_available", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "licensepools", "licenses_reserved", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "licensepools",
        "patrons_in_hold_queue",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "licenses", "license_pool_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("loans", "patron_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "loans", "license_pool_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "workgenres", "genre_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("workgenres", "work_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workgenres", "work_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("workgenres", "genre_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "loans", "license_pool_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("loans", "patron_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "licenses", "license_pool_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "licensepools",
        "patrons_in_hold_queue",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "licensepools", "licenses_reserved", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "licensepools", "licenses_available", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "licensepools", "licenses_owned", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "licensepools", "identifier_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "licensepools", "data_source_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("lanes", "display_name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "holds", "license_pool_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("holds", "patron_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "equivalentscoveragerecords",
        "equivalency_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "equivalents", "input_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "editions", "primary_identifier_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "editions", "data_source_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "customlists",
        "auto_update_status",
        existing_type=postgresql.ENUM(
            "init", "updated", "repopulate", name="auto_update_status"
        ),
        nullable=True,
    )
    # ### end Alembic commands ###
