"""initial

Revision ID: 6f96516c7a7b
Revises:
Create Date: 2022-10-06 06:50:45.512958+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "6f96516c7a7b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_libraryalias_language", table_name="libraryalias")
    op.drop_index("ix_libraryalias_library_id", table_name="libraryalias")
    op.drop_index("ix_libraryalias_name", table_name="libraryalias")
    op.drop_table("libraryalias")
    op.drop_index("ix_complaints_license_pool_id", table_name="complaints")
    op.drop_index("ix_complaints_source", table_name="complaints")
    op.drop_index("ix_complaints_type", table_name="complaints")
    op.drop_table("complaints")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "complaints",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("license_pool_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("detail", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "resolved",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["license_pool_id"],
            ["licensepools.id"],
            name="complaints_license_pool_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="complaints_pkey"),
    )
    op.create_index("ix_complaints_type", "complaints", ["type"], unique=False)
    op.create_index("ix_complaints_source", "complaints", ["source"], unique=False)
    op.create_index(
        "ix_complaints_license_pool_id", "complaints", ["license_pool_id"], unique=False
    )
    op.create_table(
        "libraryalias",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("library_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(length=3), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["library_id"], ["libraries.id"], name="libraryalias_library_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="libraryalias_pkey"),
        sa.UniqueConstraint(
            "library_id",
            "name",
            "language",
            name="libraryalias_library_id_name_language_key",
        ),
    )
    op.create_index("ix_libraryalias_name", "libraryalias", ["name"], unique=False)
    op.create_index(
        "ix_libraryalias_library_id", "libraryalias", ["library_id"], unique=False
    )
    op.create_index(
        "ix_libraryalias_language", "libraryalias", ["language"], unique=False
    )
    # ### end Alembic commands ###
