FROM ghcr.io/REPOSITORY_OWNER/docker-base:TAG

ENV SIMPLIFIED_DB_TASK "ignore"
ENV LANG=C.UTF-8

RUN /bin/bash -c "/ls_build/nginx.sh \
      && /ls_build/uwsgi.sh \
      && rm -rf /ls_build && /bd_build/cleanup.sh"

VOLUME /var/log
WORKDIR /home/simplified/circulation
EXPOSE 80

CMD ["/sbin/my_init"]
