name: "Jira Release Sync"
description: "Create Jira version, link release notes, and update fixVersions"

inputs:
  jira-base-url:
    description: "Jira base URL"
    required: true
  jira-user-email:
    description: "Jira user email"
    required: true
  jira-api-token:
    description: "Jira API token"
    required: true
  jira-project-key:
    description: "Jira project key"
    required: false
    default: "PP"
  release-name:
    description: "Jira release/version name"
    required: true
  release-url:
    description: "GitHub release URL"
    required: true
  release-body:
    description: "GitHub release body"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-user-email }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}

    - name: Create New Jira Release
      shell: bash
      env:
        JIRA_PROJECT_KEY: ${{ inputs.jira-project-key }}
        RELEASE_NAME: ${{ inputs.release-name }}
      run: |
        curl -X POST \
          --url "${{ inputs.jira-base-url }}/rest/api/3/version" \
          --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "{
            \"name\": \"${RELEASE_NAME}\",
            \"description\": \"Release created from GitHub build.\",
            \"project\": \"${JIRA_PROJECT_KEY}\",
            \"released\": false
          }"

    - name: Link GitHub Release to Jira Version
      shell: bash
      env:
        JIRA_PROJECT_KEY: ${{ inputs.jira-project-key }}
        RELEASE_NAME: ${{ inputs.release-name }}
        RELEASE_URL: ${{ inputs.release-url }}
      run: |
        # 1. Get the Version ID from Jira based on the name
        VERSION_ID=$(curl --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --url "${{ inputs.jira-base-url }}/rest/api/3/project/${JIRA_PROJECT_KEY}/versions" \
          | jq -r ".[] | select(.name == \"$RELEASE_NAME\") | .id")
        # 2. Add the GitHub Release link to the "Related Work" section
        curl --request POST \
          --url "${{ inputs.jira-base-url }}/rest/api/3/version/$VERSION_ID/remotelink" \
          --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "{
            \"title\": \"GitHub Release Notes\",
            \"url\": \"${RELEASE_URL}\",
            \"type\": \"release notes\"
          }"

    - name: Extract Jira Keys and Update Issues
      shell: bash
      env:
        JIRA_PROJECT_KEY: ${{ inputs.jira-project-key }}
        RELEASE_NAME: ${{ inputs.release-name }}
        RELEASE_BODY: ${{ inputs.release-body }}
      run: |
        KEYS=$(echo "${RELEASE_BODY}" | grep -oE "${JIRA_PROJECT_KEY}-[0-9]+" | sort -u)
        if [ -z "$KEYS" ]; then
          echo "No Jira keys found."
          exit 0
        fi
        for KEY in $KEYS; do
          curl --request PUT \
            --url "${{ inputs.jira-base-url }}/rest/api/3/issue/$KEY" \
            --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data "{\"update\": {\"fixVersions\": [{\"add\": {\"name\": \"$RELEASE_NAME\"}}]}}"
        done
