name: "Jira Release Sync"
description: "Create Jira version, link release notes, and update fixVersions"

inputs:
  jira-base-url:
    description: "Jira base URL"
    required: true
  jira-user-email:
    description: "Jira user email"
    required: true
  jira-api-token:
    description: "Jira API token"
    required: true
  jira-project-key:
    description: "Jira project key"
    required: false
    default: "PP"
  release-name:
    description: "Jira release/version name"
    required: true
  release-url:
    description: "GitHub release URL"
    required: true
  release-body:
    description: "GitHub release body"
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Jira
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ inputs.jira-base-url }}
        JIRA_USER_EMAIL: ${{ inputs.jira-user-email }}
        JIRA_API_TOKEN: ${{ inputs.jira-api-token }}

    - name: Create New Jira Release
      shell: bash
      run: |
        curl -X POST \
          --url "${{ inputs.jira-base-url }}/rest/api/3/version" \
          --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "{
            \"name\": \"${{ inputs.release-name }}\",
            \"description\": \"Release created from GitHub build.\",
            \"project\": \"${{ inputs.jira-project-key }}\",
            \"released\": false
          }"

    - name: Link GitHub Release to Jira Version
      shell: bash
      run: |
        # 1. Get the Version ID from Jira based on the name
        VERSION_ID=$(curl --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --url "${{ inputs.jira-base-url }}/rest/api/3/project/${{ inputs.jira-project-key }}/versions" \
          | jq -r ".[] | select(.name == \"${{ inputs.release-name }}\") | .id")
        # 2. Add the GitHub Release link to the "Related Work" section
        curl --request POST \
          --url "${{ inputs.jira-base-url }}/rest/api/3/version/$VERSION_ID/remotelink" \
          --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data "{
            \"title\": \"GitHub Release Notes\",
            \"url\": \"${{ inputs.release-url }}\",
            \"type\": \"release notes\"
          }"

    - name: Extract Jira Keys and Update Issues
      shell: bash
      run: |
        KEYS=$(echo "${{ inputs.release-body }}" | grep -oE "${{ inputs.jira-project-key }}-[0-9]+" | sort -u)
        if [ -z "$KEYS" ]; then
          echo "No Jira keys found."
          exit 0
        fi
        for KEY in $KEYS; do
          curl --request PUT \
            --url "${{ inputs.jira-base-url }}/rest/api/3/issue/$KEY" \
            --user "${{ inputs.jira-user-email }}:${{ inputs.jira-api-token }}" \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --data "{\"update\": {\"fixVersions\": [{\"add\": {\"name\": \"${{ inputs.release-name }}\"}}]}}"
        done
