#!/bin/bash
set -e

cd /var/www/circulation
source env/bin/activate
exec env/bin/celery -A "core.celery.worker.app" beat --uid 1000 --gid 1000 --logfile /var/log/celery/beat.log -s /var/run/celery/beat-schedule
