#!/bin/bash
set -e

# Set the working directory to the root of the project
cd /var/www/circulation
source env/bin/activate

# Make sure the log directory exists and is writable
mkdir -p /var/log/celery
chown palace:adm /var/log/celery

# Make sure the run directory exists and is writable
mkdir -p /var/run/celery
chown palace:palace /var/run/celery

# Start the celery beat process
exec env/bin/celery -A "palace.manager.celery.app" beat --uid palace --gid palace --logfile /var/log/celery/beat.log -s /var/run/celery/beat-schedule
