# WARNING!
# This file is dynamically generated during the CI build process.
# Any changes made here will be overwritten. Do not edit this file manually.

__version__ = "0.0.0.dev0"
__commit__: str | None = None
