/var/log/simplified/*.log {
    missingok
    daily
    maxsize 500M
    rotate 13
    copytruncate
    compress
    delaycompress
    notifempty
    dateext
    dateformat -%Y%m%dT%H%M%S
    maxage 26
}

/var/log/uwsgi/*.log {
    missingok
    daily
    maxsize 500M
    rotate 13
    copytruncate
    compress
    delaycompress
    notifempty
    dateext
    dateformat -%Y%m%dT%H%M%S
    maxage 26
}
