#!/bin/bash
set -e

mkdir -p /var/log/uwsgi
chown root:adm /var/log/uwsgi
touch /var/log/uwsgi/uwsgi.log
chown palace:adm /var/log/uwsgi/uwsgi.log
chmod 644 /var/log/uwsgi/uwsgi.log
exec /var/www/circulation/env/bin/uwsgi --ini /etc/uwsgi.ini
