#!/bin/bash
set -e

cd /var/www/circulation
source env/bin/activate
exec env/bin/celery -A "core.celery.worker.app" worker --uid 1000 --gid 1000 --concurrency 1 --hostname high@%h -Q high --logfile /var/log/celery/high.log
