#!/bin/bash
set -e

# Set the working directory to the root of the project
cd /var/www/circulation
source env/bin/activate

# Make sure the log directory exists and is writable
mkdir -p /var/log/celery
chown 1000:adm /var/log/celery

# Start the celery worker
exec env/bin/celery -A "core.celery.worker.app" worker --uid 1000 --gid 1000 --concurrency 1 --hostname high@%h -Q high --logfile /var/log/celery/high.log
