#!/bin/bash
set -e

# Set the working directory to the root of the project
cd /var/www/circulation
source env/bin/activate

# Start the cloudwatch celery process
exec env/bin/celery -A "palace.manager.celery.app" events -c "palace.manager.celery.monitoring.Cloudwatch" -F 60 --uid palace --gid palace  --logfile /var/log/celery/cloudwatch.log
