name: 'Poetry'
description: 'Install python poetry'

inputs:
  version:
    description: "Version of poetry to install"
    required: false
    default: "1.7.1"

outputs:
  version:
    description: "Installed version"
    value: ${{ steps.poetry-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ runner.temp }}/poetry
        key: ${{ runner.os }}-poetry-install-${{ inputs.version }}

    - run: curl -sSL https://install.python-poetry.org | python - --yes --version ${{ inputs.version }}
      env:
        POETRY_HOME: ${{ runner.temp }}/poetry
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash

    - run: echo "$POETRY_HOME/bin" >> $GITHUB_PATH
      env:
        POETRY_HOME: ${{ runner.temp }}/poetry
      shell: bash

    - id: poetry-version
      run: echo "version=$(poetry --version)" >> $GITHUB_OUTPUT
      shell: bash
