name: 'Poetry'
description: 'Install python poetry'

inputs:
  version:
    description: "Version of poetry to install"
    required: false
    default: "1.5.1"

outputs:
  version:
    description: "Installed version"
    value: ${{ steps.poetry-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - run: |
        curl -sSL https://install.python-poetry.org | python - --yes --version ${{ inputs.version }}
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - id: poetry-version
      run: echo "version=$(poetry --version)" >> $GITHUB_OUTPUT
      shell: bash
