name: Jira Release Sync
on:
  release:
    types: [published]
jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Sync release to Jira
        uses: ThePalaceProject/github-actions/jira-release-sync@v1
        with:
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}

          release-name: "CM ${{ github.event.release.tag_name }}"
          release-url: ${{ github.event.release.html_url }}
          release-body: ${{ github.event.release.body }}
